create table if not exists public.quiz_question_reviews (
  question_key text primary key,
  review jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.quiz_question_feedback (
  id bigint generated by default as identity primary key,
  question_key text not null,
  category text not null,
  rating smallint not null check (rating in (-1, 1)),
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_question_outcomes (
  id bigint generated by default as identity primary key,
  question_key text not null,
  category text not null,
  is_correct boolean not null,
  created_at timestamptz not null default now()
);

create index if not exists quiz_question_feedback_question_idx
  on public.quiz_question_feedback (question_key, created_at desc);
alter table public.quiz_question_reviews enable row level security;
alter table public.quiz_question_feedback enable row level security;
alter table public.quiz_question_outcomes enable row level security;
revoke all on public.quiz_question_reviews from anon, authenticated;
revoke all on public.quiz_question_feedback from anon, authenticated;
revoke all on public.quiz_question_outcomes from anon, authenticated;
